portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('projects/', include('projects.urls')),
]

projects/urls.py
from django.urls import path
from projects import views

app_name = 'projects'

urlpatterns = [
    path('', views.all_projects, name='all_projects'),
    path('<int:pk>', views.project_details, name='project_details'),
]

projects/models.py
from django.db import models

# Create your models here.

class Project(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    technology = models.CharField(max_length=20)
    image = models.CharField(max_length=100)

projects/views.py
from django.shortcuts import render
from projects.models import Project

# Create your views here.
def all_projects(request):
    # Query the DataBase
    project = Project.objects.all()
    return render(request, 'projects/all_projects.html', {'project':project})

def project_details(request, pk):
    project = Project.objects.get(pk=pk)
    return render(request, 'projects/proj_details.html', {'project':project})

projects/templates/projects/all_projects.html
{% extends 'projects/base.html' %}

{% load static %}

{%  block content %}

<h1>Projects</h1>
    <div class="row">
    {% for proj in project %}
        <div class="col-md-4">
            <div class="card mb-2">
                <img class="card-img-top" src="{% static proj.image %}">
                <div class="card-body">
                    <h5 class="card-title">{{ proj.title }}</h5>
                    <p class="card-text">{{ proj.description }}</p>
                    <a href="{% url 'projects:project_details' proj.pk %}" class="btn btn-primary">
                        Read More
                    </a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>

{% endblock %}

projects/templates/projects/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Portfolio</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
    {% block content %}


    {% endblock %}
</body>
</html>

projects/templates/projects/proj_details.html
{% extends 'projects/base.html' %}

{% load static %}

{% block content %}

    <img src="{% static project.image %}" alt="Project Image">
    <h1>{{ project.title }}</h1>
    <p>{{ project.description }}</p>
    <p>{{ project.technology }}</p>

{% endblock %}